// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722203736_TheLastCreateOrUpdatesInModel")]
    partial class TheLastCreateOrUpdatesInModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.booking", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("booking_number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("cancellation_reason_details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("cancellation_reason_type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("cancelled_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<decimal>("discount_amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("payment_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("unpaid");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("total_price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("PK__bookings__3213E83F6EE64705");

                    b.HasIndex(new[] { "user_id", "status" }, "IX_bookings_user_status");

                    b.HasIndex(new[] { "booking_number" }, "UQ_bookings_number")
                        .IsUnique();

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("Domain.Entities.car", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("brand_id")
                        .HasColumnType("int");

                    b.Property<int>("car_category_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("dropoff_location_id")
                        .HasColumnType("int");

                    b.Property<string>("fuel_type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("pickup_location_id")
                        .HasColumnType("int");

                    b.Property<decimal>("price_per_day")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("seats_count")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("draft");

                    b.Property<string>("transmission")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("year")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__cars__3213E83FD29F8504");

                    b.HasIndex("brand_id");

                    b.HasIndex("car_category_id");

                    b.HasIndex("dropoff_location_id");

                    b.HasIndex("pickup_location_id");

                    b.ToTable("cars");
                });

            modelBuilder.Entity("Domain.Entities.car_booking", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("booking_id")
                        .HasColumnType("bigint");

                    b.Property<long>("car_id")
                        .HasColumnType("bigint");

                    b.Property<string>("driver_name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("dropoff_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("dropoff_location_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("pickup_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("pickup_location_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__car_book__3213E83FE8D298FB");

                    b.HasIndex("car_id");

                    b.HasIndex("dropoff_location_id");

                    b.HasIndex("pickup_location_id");

                    b.HasIndex(new[] { "booking_id" }, "UQ_car_bookings_booking")
                        .IsUnique();

                    b.ToTable("car_bookings");
                });

            modelBuilder.Entity("Domain.Entities.car_booking_extra", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("car_booking_id")
                        .HasColumnType("bigint");

                    b.Property<int>("car_extra_id")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("id")
                        .HasName("PK__car_book__3213E83F3CA189D1");

                    b.HasIndex("car_booking_id");

                    b.HasIndex("car_extra_id");

                    b.ToTable("car_booking_extras");
                });

            modelBuilder.Entity("Domain.Entities.car_brand", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id")
                        .HasName("PK__car_bran__3213E83FC4C36A9B");

                    b.HasIndex(new[] { "name" }, "UQ_car_brands_name")
                        .IsUnique();

                    b.ToTable("car_brands");
                });

            modelBuilder.Entity("Domain.Entities.car_category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id")
                        .HasName("PK__car_cate__3213E83FE7D737A6");

                    b.HasIndex(new[] { "name" }, "UQ_car_categories_name")
                        .IsUnique();

                    b.ToTable("car_categories");
                });

            modelBuilder.Entity("Domain.Entities.car_extra", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("pricing_type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("id")
                        .HasName("PK__car_extr__3213E83F91415630");

                    b.ToTable("car_extras");
                });

            modelBuilder.Entity("Domain.Entities.car_image", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("car_id")
                        .HasColumnType("bigint");

                    b.Property<int>("sort_order")
                        .HasColumnType("int");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id")
                        .HasName("PK__car_imag__3213E83F1A84F5DE");

                    b.HasIndex("car_id");

                    b.ToTable("car_images");
                });

            modelBuilder.Entity("Domain.Entities.car_pricing_tier", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("car_id")
                        .HasColumnType("bigint");

                    b.Property<int>("from_hours")
                        .HasColumnType("int");

                    b.Property<decimal>("price_per_hour")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("to_hours")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__car_pric__3213E83F05E65D4C");

                    b.HasIndex("car_id");

                    b.ToTable("car_pricing_tiers");
                });

            modelBuilder.Entity("Domain.Entities.favorite", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("added_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<long>("item_id")
                        .HasColumnType("bigint");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("PK__favorite__3213E83F3AE46643");

                    b.HasIndex(new[] { "user_id", "category", "item_id" }, "UQ_favorites")
                        .IsUnique();

                    b.ToTable("favorites");
                });

            modelBuilder.Entity("Domain.Entities.flight", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("arrival_at_utc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("base_price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("cabin_class")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("economy");

                    b.Property<string>("carrier_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<DateTime>("departure_at_utc")
                        .HasColumnType("datetime2");

                    b.Property<string>("destination_airport_code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("destination_city")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("duration_minutes")
                        .HasColumnType("int");

                    b.Property<string>("flight_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("origin_airport_code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("origin_city")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("seats_available")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("scheduled");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__flights__3213E83F33D7A2D7");

                    b.HasIndex(new[] { "origin_airport_code", "destination_airport_code", "departure_at_utc" }, "IX_flights_route_departure");

                    b.ToTable("flights");
                });

            modelBuilder.Entity("Domain.Entities.flight_booking", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("booking_id")
                        .HasColumnType("bigint");

                    b.Property<long>("flight_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long?>("return_flight_id")
                        .HasColumnType("bigint");

                    b.Property<string>("trip_type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("id")
                        .HasName("PK__flight_b__3213E83FA547652B");

                    b.HasIndex("flight_id");

                    b.HasIndex("return_flight_id");

                    b.HasIndex(new[] { "booking_id" }, "UQ_flight_bookings_booking")
                        .IsUnique();

                    b.ToTable("flight_bookings");
                });

            modelBuilder.Entity("Domain.Entities.flight_booking_passenger", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("flight_booking_id")
                        .HasColumnType("bigint");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("passport_number")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("title")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.HasKey("id")
                        .HasName("PK__flight_b__3213E83F11541365");

                    b.HasIndex("flight_booking_id");

                    b.ToTable("flight_booking_passengers");
                });

            modelBuilder.Entity("Domain.Entities.hotel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<TimeOnly?>("check_in_time")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("check_out_time")
                        .HasColumnType("time");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("location_id")
                        .HasColumnType("int");

                    b.Property<string>("main_image_url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte?>("star_rating")
                        .HasColumnType("tinyint");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("draft");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__hotels__3213E83F0A769D6A");

                    b.HasIndex("location_id");

                    b.HasIndex(new[] { "slug" }, "UQ_hotels_slug")
                        .IsUnique();

                    b.ToTable("hotels");
                });

            modelBuilder.Entity("Domain.Entities.hotel_booking", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long>("booking_id")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("check_in_date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("check_out_date")
                        .HasColumnType("date");

                    b.Property<int>("guests_adults")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("guests_children")
                        .HasColumnType("int");

                    b.Property<decimal>("price_per_night")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<long>("room_id")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("PK__hotel_bo__3213E83F0F36DF05");

                    b.HasIndex("room_id");

                    b.HasIndex(new[] { "booking_id" }, "UQ_hotel_bookings_booking")
                        .IsUnique();

                    b.ToTable("hotel_bookings");
                });

            modelBuilder.Entity("Domain.Entities.hotel_image", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("hotel_id")
                        .HasColumnType("bigint");

                    b.Property<int>("sort_order")
                        .HasColumnType("int");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id")
                        .HasName("PK__hotel_im__3213E83F5E313734");

                    b.HasIndex("hotel_id");

                    b.ToTable("hotel_images");
                });

            modelBuilder.Entity("Domain.Entities.location", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address_line")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.HasKey("id")
                        .HasName("PK__location__3213E83F32EDE253");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("Domain.Entities.passenger", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("is_email_verified")
                        .HasColumnType("bit");

                    b.Property<int?>("location_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("password_hash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("refreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("refresh_token_expiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("unverified");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__users__3213E83F803EACAC");

                    b.HasIndex("location_id");

                    b.HasIndex("role_id");

                    b.HasIndex(new[] { "status" }, "IX_users_status");

                    b.HasIndex(new[] { "email" }, "UQ_users_email")
                        .IsUnique();

                    b.ToTable("passengers");
                });

            modelBuilder.Entity("Domain.Entities.payment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long>("booking_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<string>("gateway")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("pending");

                    b.Property<string>("transaction_id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id")
                        .HasName("PK__payments__3213E83FA5C35E5F");

                    b.HasIndex(new[] { "booking_id" }, "IX_payments_booking");

                    b.HasIndex(new[] { "transaction_id" }, "IX_payments_transaction");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("Domain.Entities.review", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("booking_id")
                        .HasColumnType("bigint");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long>("item_id")
                        .HasColumnType("bigint");

                    b.Property<byte>("rating")
                        .HasColumnType("tinyint");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("pending");

                    b.Property<string>("title")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("PK__reviews__3213E83F474DF86E");

                    b.HasIndex("booking_id");

                    b.HasIndex(new[] { "category", "item_id" }, "IX_reviews_category_item");

                    b.HasIndex(new[] { "user_id" }, "IX_reviews_user");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("Domain.Entities.role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id")
                        .HasName("PK__roles__3213E83F247A45DA");

                    b.HasIndex(new[] { "name" }, "UQ_roles_name")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Passenger"
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Admin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.room", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("bed_type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<long>("hotel_id")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("occupancy_adults")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int>("occupancy_children")
                        .HasColumnType("int");

                    b.Property<decimal>("price_per_night")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool>("refundable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("draft");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__rooms__3213E83FA2911DD9");

                    b.HasIndex("hotel_id");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("Domain.Entities.room_availability", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<decimal?>("price_override")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long>("room_id")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("PK__room_ava__3213E83F2D19570C");

                    b.HasIndex(new[] { "room_id", "date" }, "UQ_room_availability")
                        .IsUnique();

                    b.ToTable("room_availability");
                });

            modelBuilder.Entity("Domain.Entities.room_extra", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long>("room_id")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("PK__room_ext__3213E83F4B5F7045");

                    b.HasIndex("room_id");

                    b.ToTable("room_extras");
                });

            modelBuilder.Entity("Domain.Entities.room_image", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("room_id")
                        .HasColumnType("bigint");

                    b.Property<int>("sort_order")
                        .HasColumnType("int");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id")
                        .HasName("PK__room_ima__3213E83F658ACE73");

                    b.HasIndex("room_id");

                    b.ToTable("room_images");
                });

            modelBuilder.Entity("Domain.Entities.tour", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("cancellation_reason_details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("cancellation_reason_type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("cancelled_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("cancelled_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<string>("difficulty")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("duration_days")
                        .HasColumnType("int");

                    b.Property<string>("full_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("location_id")
                        .HasColumnType("int");

                    b.Property<string>("main_image_url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__tours__3213E83F0E0F030A");

                    b.HasIndex("location_id");

                    b.HasIndex(new[] { "slug" }, "UQ_tours_slug")
                        .IsUnique();

                    b.ToTable("tours");
                });

            modelBuilder.Entity("Domain.Entities.tour_booking", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int>("adults_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<long>("booking_id")
                        .HasColumnType("bigint");

                    b.Property<int>("children_count")
                        .HasColumnType("int");

                    b.Property<int>("infants_count")
                        .HasColumnType("int");

                    b.Property<long>("tour_schedule_id")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("PK__tour_boo__3213E83F469EEF5F");

                    b.HasIndex("tour_schedule_id");

                    b.HasIndex(new[] { "booking_id" }, "UQ_tour_bookings_booking")
                        .IsUnique();

                    b.ToTable("tour_bookings");
                });

            modelBuilder.Entity("Domain.Entities.tour_image", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int>("sort_order")
                        .HasColumnType("int");

                    b.Property<long>("tour_id")
                        .HasColumnType("bigint");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id")
                        .HasName("PK__tour_ima__3213E83FA46D7C76");

                    b.HasIndex("tour_id");

                    b.ToTable("tour_images");
                });

            modelBuilder.Entity("Domain.Entities.tour_inclusion", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<bool>("is_included")
                        .HasColumnType("bit");

                    b.Property<string>("item_text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("tour_id")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("PK__tour_inc__3213E83F53BCBFD2");

                    b.HasIndex("tour_id");

                    b.ToTable("tour_inclusions");
                });

            modelBuilder.Entity("Domain.Entities.tour_price_tier", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<decimal>("adult_price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("child_price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<decimal?>("infant_price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("tour_id")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("PK__tour_pri__3213E83FD09A27BF");

                    b.HasIndex("tour_id");

                    b.ToTable("tour_price_tiers");
                });

            modelBuilder.Entity("Domain.Entities.tour_schedule", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int>("available_slots")
                        .HasColumnType("int");

                    b.Property<string>("cancellation_reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("cancelled_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_cancelled")
                        .HasColumnType("bit");

                    b.Property<long>("price_tier_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("tour_id")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("PK__tour_sch__3213E83FF02F5E8A");

                    b.HasIndex("price_tier_id");

                    b.HasIndex(new[] { "tour_id", "start_date" }, "IX_tour_schedules_tour_start")
                        .IsUnique();

                    b.ToTable("tour_schedules");
                });

            modelBuilder.Entity("Domain.Entities.booking", b =>
                {
                    b.HasOne("Domain.Entities.passenger", "passenger")
                        .WithMany("bookings")
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("FK_bookings_user");

                    b.Navigation("passenger");
                });

            modelBuilder.Entity("Domain.Entities.car", b =>
                {
                    b.HasOne("Domain.Entities.car_brand", "brand")
                        .WithMany("cars")
                        .HasForeignKey("brand_id")
                        .IsRequired()
                        .HasConstraintName("FK_cars_brand");

                    b.HasOne("Domain.Entities.car_category", "car_category")
                        .WithMany("cars")
                        .HasForeignKey("car_category_id")
                        .IsRequired()
                        .HasConstraintName("FK_cars_category");

                    b.HasOne("Domain.Entities.location", "dropoff_location")
                        .WithMany("cardropoff_locations")
                        .HasForeignKey("dropoff_location_id")
                        .HasConstraintName("FK_cars_dropoff_location");

                    b.HasOne("Domain.Entities.location", "pickup_location")
                        .WithMany("carpickup_locations")
                        .HasForeignKey("pickup_location_id")
                        .HasConstraintName("FK_cars_pickup_location");

                    b.Navigation("brand");

                    b.Navigation("car_category");

                    b.Navigation("dropoff_location");

                    b.Navigation("pickup_location");
                });

            modelBuilder.Entity("Domain.Entities.car_booking", b =>
                {
                    b.HasOne("Domain.Entities.booking", "booking")
                        .WithOne("car_booking")
                        .HasForeignKey("Domain.Entities.car_booking", "booking_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_car_bookings_booking");

                    b.HasOne("Domain.Entities.car", "car")
                        .WithMany("car_bookings")
                        .HasForeignKey("car_id")
                        .IsRequired()
                        .HasConstraintName("FK_car_bookings_car");

                    b.HasOne("Domain.Entities.location", "dropoff_location")
                        .WithMany("car_bookingdropoff_locations")
                        .HasForeignKey("dropoff_location_id")
                        .IsRequired()
                        .HasConstraintName("FK_car_bookings_dropoff_location");

                    b.HasOne("Domain.Entities.location", "pickup_location")
                        .WithMany("car_bookingpickup_locations")
                        .HasForeignKey("pickup_location_id")
                        .IsRequired()
                        .HasConstraintName("FK_car_bookings_pickup_location");

                    b.Navigation("booking");

                    b.Navigation("car");

                    b.Navigation("dropoff_location");

                    b.Navigation("pickup_location");
                });

            modelBuilder.Entity("Domain.Entities.car_booking_extra", b =>
                {
                    b.HasOne("Domain.Entities.car_booking", "car_booking")
                        .WithMany("car_booking_extras")
                        .HasForeignKey("car_booking_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_car_booking_extras_booking");

                    b.HasOne("Domain.Entities.car_extra", "car_extra")
                        .WithMany("car_booking_extras")
                        .HasForeignKey("car_extra_id")
                        .IsRequired()
                        .HasConstraintName("FK_car_booking_extras_extra");

                    b.Navigation("car_booking");

                    b.Navigation("car_extra");
                });

            modelBuilder.Entity("Domain.Entities.car_image", b =>
                {
                    b.HasOne("Domain.Entities.car", "car")
                        .WithMany("car_images")
                        .HasForeignKey("car_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_car_images_car");

                    b.Navigation("car");
                });

            modelBuilder.Entity("Domain.Entities.car_pricing_tier", b =>
                {
                    b.HasOne("Domain.Entities.car", "car")
                        .WithMany("car_pricing_tiers")
                        .HasForeignKey("car_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_car_pricing_tiers_car");

                    b.Navigation("car");
                });

            modelBuilder.Entity("Domain.Entities.favorite", b =>
                {
                    b.HasOne("Domain.Entities.passenger", "passenger")
                        .WithMany("favorites")
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("FK_favorites_user");

                    b.Navigation("passenger");
                });

            modelBuilder.Entity("Domain.Entities.flight_booking", b =>
                {
                    b.HasOne("Domain.Entities.booking", "booking")
                        .WithOne("flight_booking")
                        .HasForeignKey("Domain.Entities.flight_booking", "booking_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_flight_bookings_booking");

                    b.HasOne("Domain.Entities.flight", "flight")
                        .WithMany("flight_bookingflights")
                        .HasForeignKey("flight_id")
                        .IsRequired()
                        .HasConstraintName("FK_flight_bookings_flight");

                    b.HasOne("Domain.Entities.flight", "return_flight")
                        .WithMany("flight_bookingreturn_flights")
                        .HasForeignKey("return_flight_id")
                        .HasConstraintName("FK_flight_bookings_return_flight");

                    b.Navigation("booking");

                    b.Navigation("flight");

                    b.Navigation("return_flight");
                });

            modelBuilder.Entity("Domain.Entities.flight_booking_passenger", b =>
                {
                    b.HasOne("Domain.Entities.flight_booking", "flight_booking")
                        .WithMany("flight_booking_passengers")
                        .HasForeignKey("flight_booking_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_flight_passengers_booking");

                    b.Navigation("flight_booking");
                });

            modelBuilder.Entity("Domain.Entities.hotel", b =>
                {
                    b.HasOne("Domain.Entities.location", "location")
                        .WithMany("hotels")
                        .HasForeignKey("location_id")
                        .IsRequired()
                        .HasConstraintName("FK_hotels_location");

                    b.Navigation("location");
                });

            modelBuilder.Entity("Domain.Entities.hotel_booking", b =>
                {
                    b.HasOne("Domain.Entities.booking", "booking")
                        .WithOne("hotel_booking")
                        .HasForeignKey("Domain.Entities.hotel_booking", "booking_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_hotel_bookings_booking");

                    b.HasOne("Domain.Entities.room", "room")
                        .WithMany("hotel_bookings")
                        .HasForeignKey("room_id")
                        .IsRequired()
                        .HasConstraintName("FK_hotel_bookings_room");

                    b.Navigation("booking");

                    b.Navigation("room");
                });

            modelBuilder.Entity("Domain.Entities.hotel_image", b =>
                {
                    b.HasOne("Domain.Entities.hotel", "hotel")
                        .WithMany("hotel_images")
                        .HasForeignKey("hotel_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_hotel_images_hotel");

                    b.Navigation("hotel");
                });

            modelBuilder.Entity("Domain.Entities.passenger", b =>
                {
                    b.HasOne("Domain.Entities.location", "location")
                        .WithMany("passengers")
                        .HasForeignKey("location_id")
                        .HasConstraintName("FK_users_location");

                    b.HasOne("Domain.Entities.role", "role")
                        .WithMany("passengers")
                        .HasForeignKey("role_id")
                        .IsRequired()
                        .HasConstraintName("FK_users_role");

                    b.Navigation("location");

                    b.Navigation("role");
                });

            modelBuilder.Entity("Domain.Entities.payment", b =>
                {
                    b.HasOne("Domain.Entities.booking", "booking")
                        .WithMany("payments")
                        .HasForeignKey("booking_id")
                        .IsRequired()
                        .HasConstraintName("FK_payments_booking");

                    b.Navigation("booking");
                });

            modelBuilder.Entity("Domain.Entities.review", b =>
                {
                    b.HasOne("Domain.Entities.booking", "booking")
                        .WithMany("reviews")
                        .HasForeignKey("booking_id")
                        .HasConstraintName("FK_reviews_booking");

                    b.HasOne("Domain.Entities.passenger", "passenger")
                        .WithMany("reviews")
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("FK_reviews_user");

                    b.Navigation("booking");

                    b.Navigation("passenger");
                });

            modelBuilder.Entity("Domain.Entities.room", b =>
                {
                    b.HasOne("Domain.Entities.hotel", "hotel")
                        .WithMany("rooms")
                        .HasForeignKey("hotel_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_rooms_hotel");

                    b.Navigation("hotel");
                });

            modelBuilder.Entity("Domain.Entities.room_availability", b =>
                {
                    b.HasOne("Domain.Entities.room", "room")
                        .WithMany("room_availabilities")
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_room_availability_room");

                    b.Navigation("room");
                });

            modelBuilder.Entity("Domain.Entities.room_extra", b =>
                {
                    b.HasOne("Domain.Entities.room", "room")
                        .WithMany("room_extras")
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_room_extras_room");

                    b.Navigation("room");
                });

            modelBuilder.Entity("Domain.Entities.room_image", b =>
                {
                    b.HasOne("Domain.Entities.room", "room")
                        .WithMany("room_images")
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_room_images_room");

                    b.Navigation("room");
                });

            modelBuilder.Entity("Domain.Entities.tour", b =>
                {
                    b.HasOne("Domain.Entities.location", "location")
                        .WithMany("tours")
                        .HasForeignKey("location_id")
                        .HasConstraintName("FK_tours_location");

                    b.Navigation("location");
                });

            modelBuilder.Entity("Domain.Entities.tour_booking", b =>
                {
                    b.HasOne("Domain.Entities.booking", "booking")
                        .WithOne("tour_booking")
                        .HasForeignKey("Domain.Entities.tour_booking", "booking_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tour_bookings_booking");

                    b.HasOne("Domain.Entities.tour_schedule", "tour_schedule")
                        .WithMany("tour_bookings")
                        .HasForeignKey("tour_schedule_id")
                        .IsRequired()
                        .HasConstraintName("FK_tour_bookings_schedule");

                    b.Navigation("booking");

                    b.Navigation("tour_schedule");
                });

            modelBuilder.Entity("Domain.Entities.tour_image", b =>
                {
                    b.HasOne("Domain.Entities.tour", "tour")
                        .WithMany("tour_images")
                        .HasForeignKey("tour_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tour_images_tour");

                    b.Navigation("tour");
                });

            modelBuilder.Entity("Domain.Entities.tour_inclusion", b =>
                {
                    b.HasOne("Domain.Entities.tour", "tour")
                        .WithMany("tour_inclusions")
                        .HasForeignKey("tour_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tour_inclusions_tour");

                    b.Navigation("tour");
                });

            modelBuilder.Entity("Domain.Entities.tour_price_tier", b =>
                {
                    b.HasOne("Domain.Entities.tour", "tour")
                        .WithMany("tour_price_tiers")
                        .HasForeignKey("tour_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tour_price_tiers_tour");

                    b.Navigation("tour");
                });

            modelBuilder.Entity("Domain.Entities.tour_schedule", b =>
                {
                    b.HasOne("Domain.Entities.tour_price_tier", "price_tier")
                        .WithMany("tour_schedules")
                        .HasForeignKey("price_tier_id")
                        .IsRequired()
                        .HasConstraintName("FK_tour_schedules_price_tier");

                    b.HasOne("Domain.Entities.tour", "tour")
                        .WithMany("tour_schedules")
                        .HasForeignKey("tour_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tour_schedules_tour");

                    b.Navigation("price_tier");

                    b.Navigation("tour");
                });

            modelBuilder.Entity("Domain.Entities.booking", b =>
                {
                    b.Navigation("car_booking");

                    b.Navigation("flight_booking");

                    b.Navigation("hotel_booking");

                    b.Navigation("payments");

                    b.Navigation("reviews");

                    b.Navigation("tour_booking");
                });

            modelBuilder.Entity("Domain.Entities.car", b =>
                {
                    b.Navigation("car_bookings");

                    b.Navigation("car_images");

                    b.Navigation("car_pricing_tiers");
                });

            modelBuilder.Entity("Domain.Entities.car_booking", b =>
                {
                    b.Navigation("car_booking_extras");
                });

            modelBuilder.Entity("Domain.Entities.car_brand", b =>
                {
                    b.Navigation("cars");
                });

            modelBuilder.Entity("Domain.Entities.car_category", b =>
                {
                    b.Navigation("cars");
                });

            modelBuilder.Entity("Domain.Entities.car_extra", b =>
                {
                    b.Navigation("car_booking_extras");
                });

            modelBuilder.Entity("Domain.Entities.flight", b =>
                {
                    b.Navigation("flight_bookingflights");

                    b.Navigation("flight_bookingreturn_flights");
                });

            modelBuilder.Entity("Domain.Entities.flight_booking", b =>
                {
                    b.Navigation("flight_booking_passengers");
                });

            modelBuilder.Entity("Domain.Entities.hotel", b =>
                {
                    b.Navigation("hotel_images");

                    b.Navigation("rooms");
                });

            modelBuilder.Entity("Domain.Entities.location", b =>
                {
                    b.Navigation("car_bookingdropoff_locations");

                    b.Navigation("car_bookingpickup_locations");

                    b.Navigation("cardropoff_locations");

                    b.Navigation("carpickup_locations");

                    b.Navigation("hotels");

                    b.Navigation("passengers");

                    b.Navigation("tours");
                });

            modelBuilder.Entity("Domain.Entities.passenger", b =>
                {
                    b.Navigation("bookings");

                    b.Navigation("favorites");

                    b.Navigation("reviews");
                });

            modelBuilder.Entity("Domain.Entities.role", b =>
                {
                    b.Navigation("passengers");
                });

            modelBuilder.Entity("Domain.Entities.room", b =>
                {
                    b.Navigation("hotel_bookings");

                    b.Navigation("room_availabilities");

                    b.Navigation("room_extras");

                    b.Navigation("room_images");
                });

            modelBuilder.Entity("Domain.Entities.tour", b =>
                {
                    b.Navigation("tour_images");

                    b.Navigation("tour_inclusions");

                    b.Navigation("tour_price_tiers");

                    b.Navigation("tour_schedules");
                });

            modelBuilder.Entity("Domain.Entities.tour_price_tier", b =>
                {
                    b.Navigation("tour_schedules");
                });

            modelBuilder.Entity("Domain.Entities.tour_schedule", b =>
                {
                    b.Navigation("tour_bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
